#!/usr/bin/env python3

#
# Copyright (C) 2026 dnshelper contributors
# SPDX-License-Identifier: GPL-3.0-or-later
#

# Register this module as the provider of the "dnshelper" service, so that
# other modules can check that it is present:
#
#   agent.list_service_providers(rdb, 'dnshelper')
#
# There is no host or port: the API is this module's actions, called with
# agent.tasks.run(). The key is removed together with the module.

import os
import agent

module_id = os.environ['MODULE_ID']

rdb = agent.redis_connect(privileged=True)
rdb.hset(f'module/{module_id}/srv/api/dnshelper', mapping={
    'api': 'actions',
    'version': '1',
})
