#!/usr/bin/env python3

#
# Copyright (C) 2026 dnshelper contributors
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys

here = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(here, '..', '..', 'pypkg'))
import dnshelper_lib

dnshelper_lib.run(os.path.basename(here))
